export const EDIT_CHANGE = 'EDIT_CHANGE';
export const DELETE_PICTURE = 'DELETE_PICTURE';
export const FETCH_ALBUMS_REQUEST = 'FETCH_ALBUMS_REQUEST';
export const FETCH_ALBUMS_FAILURE = 'FETCH_ALBUMS_FAILURE';
export const FETCH_ALBUMS_SUCCESS = 'FETCH_ALBUMS_SUCCESS';
export const FETCH_ALBUM_REQUEST = 'FETCH_ALBUM_REQUEST';
export const FETCH_ALBUM_FAILURE = 'FETCH_ALBUM_FAILURE';
export const FETCH_ALBUM_SUCCESS = 'FETCH_ALBUM_SUCCESS';
export const BACK_TO_ALBUMS_VIEW = "BACK_TO_ALBUMS_VIEW";
export const SIGN_IN = 'SIGN_IN';
export const UPLOAD_FORM_VISIBLE = "UPLOAD_FORM_VISIBLE";
export const FETCH_UPLOAD_SUCCESS = "FETCH_UPLOAD_SUCCESS";
export const FETCH_UPLOAD_FAILURE = "FETCH_UPLOAD_FAILURE";
export const FETCH_UPLOAD_REQUEST = "FETCH_UPLOAD_REQUEST";

